export const requiredField = 'Field is required';
export const emailMin = 'Min 6 symbols';
export const emailMax = 'Max symbols is 30';
export const emailNotValid = 'Email is not valid';
export const userNameMin = 'Min 2 symbols';
export const userNameMax = 'Max symbols is 20';
export const phoneMin = 'Min 5 symbols';
export const phoneMax = 'Max symbols is 20';
export const phoneNotValid = 'Phone is not valid';
